### ISSUE TITLE
Suggestion: local-only offers/requests that you can select to view

### ISSUE THREAD

**Issue by tog22** [patbl/Skillshare.im#33]
Not saying it's necessarily worth the time to add, but thought I might as well put it down as a suggestion :smile: 

As an example, I could add 'Request: basic office/household good X' (for the Charity Science office/house), and this would only be visible to Vancouver EAs who chose to look at Vancouver-only offers/requests (many of whom'd be happy to freecycle stuff through Charity Science and other EAs).

**Comment by patbl** [comment]
Thanks for the suggestion, but it's probably not going to happen because no one is using the app lol.
